defmodule TagIp.Repo.Migrations.CreateMountingProfiles do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
  drop_if_exists table(:profils_montage), mode: :cascade

    create table(:mounting_profiles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :description, :text
      add :reporting_interval, :text, null: false
      add :object_type, :text, null: false
      add :voltage_min, :bigint, null: false, default: 10800
      add :voltage_max, :bigint, null: false, default: 32000
      add :buzzer, :boolean, null: false, default: false
      add :fuel_probe_type, :text, null: false, default: "none"
      add :geofence_enabled, :boolean, null: false, default: false
      add :driver_id_type, :text, null: false, default: "none"
      add :active, :boolean, null: false, default: true
      add :organization_id, :uuid, null: false
      add :author_id, :uuid, null: false
      add :seeded_from_id, :uuid

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    #drop constraint(:compatibilites, "compatibilites_profil_montage_id_fkey")

    alter table(:compatibilites) do
      modify :score_compatibilite, :bigint, default: nil

      modify :profil_montage_id,
             references(:mounting_profiles,
               column: :id,
               name: "compatibilites_profil_montage_id_fkey",
               type: :uuid
             )
    end
  end

  def down do
    drop constraint(:compatibilites, "compatibilites_profil_montage_id_fkey")

    alter table(:compatibilites) do
      modify :profil_montage_id,
             references(:profils_montage,
               column: :id,
               name: "compatibilites_profil_montage_id_fkey",
               type: :uuid
             )

      modify :score_compatibilite, :bigint, default: 0
    end

    drop table(:mounting_profiles)

    # Rollback would require recreating the table manually
  end
end
