defmodule TagIp.Repo.Migrations.AddInitialTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:profils_montage, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :nom, :text, null: false
      add :type_vehicule, :text, null: false
      add :alimentation, :text, null: false
      add :capteurs, {:array, :text}, default: []
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:modeles_traceur, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :nom, :text, null: false
      add :reference, :text, null: false
      add :types_vehicule_compatibles, {:array, :text}, default: []
      add :alimentations_compatibles, {:array, :text}, default: []
      add :capteurs_supportes, {:array, :text}, default: []
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:compatibilites, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :score_compatibilite, :bigint, null: false, default: 0
      add :details, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :profil_montage_id,
          references(:profils_montage,
            column: :id,
            name: "compatibilites_profil_montage_id_fkey",
            type: :uuid
          ),
          null: false

      add :modele_traceur_id,
          references(:modeles_traceur,
            column: :id,
            name: "compatibilites_modele_traceur_id_fkey",
            type: :uuid
          ),
          null: false
    end
  end

  def down do
    drop constraint(:compatibilites, "compatibilites_profil_montage_id_fkey")

    drop constraint(:compatibilites, "compatibilites_modele_traceur_id_fkey")

    drop table(:compatibilites)

    drop table(:modeles_traceur)

    drop table(:profils_montage)
  end
end
