defmodule TagIp.Repo.Migrations.CreateTrackableTables do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:trackable_types, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :label, :text, null: false
      add :description, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create table(:trackable_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :code, :text, null: false
      add :name, :text, null: false
      add :trackable_type_slug, :text, null: false
      add :manufacturer_id, :uuid
      add :activity_model_id, :uuid
      add :driver_id_type_id, :uuid
      add :organization_id, :uuid
      add :monitors, :text
      add :display_name, :text
      add :green_driving_id, :uuid
      add :fuel_cap_id, :uuid
      add :sort_order, :bigint

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    alter table(:compatibilites) do
      modify :score_compatibilite, :bigint, default: 0
    end
  end

  def down do
    alter table(:compatibilites) do
      modify :score_compatibilite, :bigint, default: nil
    end

    drop table(:trackable_categories)

    drop table(:trackable_types)
  end
end
