defmodule TagIp.Repo.Migrations.UpdateProfilTypes do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:mounting_profiles) do
      remove :seeded_from_id
      remove :author_id
      remove :active
      modify :organization_id, :uuid, null: true
      modify :driver_id_type, :text, null: true, default: nil
      modify :geofence_enabled, :boolean, null: true
      modify :fuel_probe_type, :text, null: true, default: nil
      modify :buzzer, :boolean, null: true
      modify :voltage_max, :float, null: true, default: nil
      modify :voltage_min, :float, null: true, default: nil
      modify :object_type, :text, null: true
      modify :reporting_interval, :text, null: true
    end
  end

  def down do
    alter table(:mounting_profiles) do
      modify :reporting_interval, :text, null: false
      modify :object_type, :text, null: false
      modify :voltage_min, :bigint, null: false, default: 10800
      modify :voltage_max, :bigint, null: false, default: 32000
      modify :buzzer, :boolean, null: false
      modify :fuel_probe_type, :text, null: false, default: "none"
      modify :geofence_enabled, :boolean, null: false
      modify :driver_id_type, :text, null: false, default: "none"
      modify :organization_id, :uuid, null: false
      add :active, :boolean, null: false, default: true
      add :author_id, :uuid, null: false
      add :seeded_from_id, :uuid
    end
  end
end
